"""
配置文件包，导出 settings 模块中的配置变量
"""

from .settings import (
    OPENAI_API_KEY,
    OPENAI_BASE_URL,
    CHAT_MODEL,
    PICOVOICE_ACCESS_KEY,
    RECOGNIZER_ENGINE,
    WAKE_WORD_PATHS,
    CUSTOM_RECOGNIZER_API_KEY,
    CUSTOM_RECOGNIZER_BASE_URL,
    CUSTOM_RECOGNIZER_MODEL,
    MQTT_BROKER,
    MQTT_PORT,
    MQTT_USERNAME,
    MQTT_PASSWORD,
    # GSV_API_KEY,
    GSV_BASE_URL,
    REF_AUDIO_PATH,
    PROMPT_TEXT,
    PROMPT_LANG,
    # GSV_MODEL,
    # GSV_VOICE,
    WAKE_SOUND_PATH,
    DOWN_SOUND_PATH,
)

__all__ = [
    "OPENAI_API_KEY",
    "OPENAI_BASE_URL",
    "CHAT_MODEL",
    "PICOVOICE_ACCESS_KEY",
    "RECOGNIZER_ENGINE",
    "WAKE_WORD_PATHS",
    "CUSTOM_RECOGNIZER_API_KEY",
    "CUSTOM_RECOGNIZER_BASE_URL",
    "CUSTOM_RECOGNIZER_MODEL",
    "MQTT_BROKER",
    "MQTT_PORT",
    "MQTT_USERNAME",
    "MQTT_PASSWORD",
    # "GSV_API_KEY"
    "GSV_BASE_URL",
    "REF_AUDIO_PATH",
    "PROMPT_TEXT",
    "PROMPT_LANG",
    # "GSV_MODEL",
    # "GSV_VOICE",
    "WAKE_SOUND_PATH",
    "DOWN_SOUND_PATH",
]